import streamlit as st

st.title("Disclaimer")
st.markdown("""
## Liability Disclaimer  

**Please read and acknowledge the following before proceeding**:  

1. **Personal Responsibility**: By using this assessment tool, you acknowledge that you are responsible for ensuring that any data entered, including job profiles and assessment information, complies with applicable data privacy regulations (e.g., GDPR). This includes ensuring that any personal information (such as candidate names, specific company details, or other identifying information) is anonymized to protect third-party privacy.
1. **No Hiring Decisions**: This tool is intended solely as a self-assessment resource to evaluate fit with specific job profiles. It is not intended to provide hiring recommendations or make decisions on behalf of any organization. Any insights or results generated by the assessment are for personal use only and should not replace formal assessment or hiring processes.
1. **Liability Limitation**: We assume no responsibility or liability for any direct, indirect, or consequential damages resulting from the use of this tool, including any decisions made based on the assessment outcomes. By using the assessment, you agree that any risks associated with data entry, usage, or interpretations are solely yours.

## Data Usage Policy  

**Before proceeding, please review our data usage practices below**:  

1. **Data Privacy and Anonymization**: The assessment tool makes a best effort to anonymize identifying information within your input data. For example, specific company names or other proper nouns may be generalized. However, it remains your responsibility to review and anonymize sensitive information before submission.
1. **Temporary Data Storage**: Input data and generated assessments are stored temporarily to provide you with custom output. While the tool does not intentionally store personally identifiable information (PII), we recommend avoiding unnecessary submission of sensitive data, such as names or addresses. The data is automatically anonymized to the best of our ability before processing.
1. **User Rights and Data Deletion**: Users can request deletion of any data that may be retained by contacting us and providing identifying information (such as an email address or unique assessment ID). We will make a best effort to delete such data upon request, although anonymized and aggregated data may be retained for general analytics without identifying users.
1. **Analytics and Aggregated Insights**: To improve the assessment experience, anonymized and aggregated data from assessments (e.g., skill frequency, job profile types) may be retained for general analytics purposes. No personal identifiers are included in these analytics, and data is used only to understand general trends.
""", )