# Use the official lightweight Python image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy only the essential files for production
COPY . /app

# Install dependencies in a non-editable mode for production
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Streamlit will run on
EXPOSE 8501

# Run the Streamlit application
CMD ["streamlit", "run", "src/app.py"]
